---
- name: Create user group
  group:
    name: "{{ user.group}}"

- name: Create user
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user_password|password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    groups: wheel
    append: yes
